### ISSUE TITLE
missing anime

### ISSUE THREAD

**Issue by Py-Monsters** [Enime-Project/api.enime.moe#12]
When I was testing out the api I noticed that some of the animes are missing. I got a reasoning to that which is that they had nsfw tag.
Would you please try adding an option to allow animes with nsfw tag

**Comment by NADESHIKON** [comment]
Sorry Enime API does not store nfsw (I can safely assume they're hentai) anime, you have to fork this and host a modified version yourself.

**Comment by Py-Monsters** [comment]
They are not "hentai" (I found them on several "anime" sites and on mal, anilist and kitsu)

**Comment by NADESHIKON** [comment]
For example?

**Comment by Py-Monsters** [comment]
I found an alternative way of doing it. Sorry for the inconvenience.
