### ISSUE TITLE
Documentation about api

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [Enime-Project/api.enime.moe#14]
I was previously using the consumet API for anime data. Now as they have declared to shut down the API this September it is a problem for me so I found out where they were getting their data and I found out about Enime.  So I would like to know how to use your hosted API.

**Comment by illusionTBA** [comment]
https://docs.enime.moe -- the website and its also open sourced [here](https://github.com/Enime-Project/docs.enime.moe)

**Comment by Shuvadip-Ghosh** [comment]
i would like to ask something more that slug get from this link https://api.enime.moe/mapping/anilist/20 and the gogoanime id same for a particular anime???

**Comment by illusionTBA** [comment]
So what

**Comment by Shuvadip-Ghosh** [comment]
I was asking about all anime and not particular anime sorry my bad
