### ISSUE TITLE
delay in enime adding provider zoro to recent episodes

### ISSUE THREAD

**Issue by SocialDropout** [Enime-Project/api.enime.moe#15]
Is the much delay in Enime adding stream links to recent episodes compared to Zoro an issue or expected behavior? I thought they should be added almost simultaneously since Enime is scraping Zoro.

**Comment by NADESHIKON** [comment]
There shouldn't be, unless Zoro itself is being slow.

**Comment by SocialDropout** [comment]
> There shouldn't be, unless Zoro itself is being slow.

I've noticed that sometimes Zoro posts a new anime ep but enime api doesn't have it in the recent list. It gets added later on tho.
