### ISSUE TITLE
how to decrypt rapid cloud sources

### ISSUE THREAD

**Issue by thullyDev** [Enime-Project/api.enime.moe#16]
Hi Fellow programmers, I have been trying to decrypt Rapid cloud sources for 9anime and Zoro, but I keep reaching a dead end in my solutions, and I tried looking at your code, but maybe I am just too stupid, because I couldnt have any crucial clues, that would help decrypt rapid-cloud sources...

### Ok, Here is what I was trying to do...

I was getting the anime episode id from [https://9animetv.to/watch/golden-kamuy-season-4-18162?ep=101574](https://9animetv.to/watch/golden-kamuy-season-4-18162?ep=101574) which is episodeId = **101574**, and passing it to [https://zoro.to/ajax/v2/episode/servers?episodeId=101574](https://zoro.to/ajax/v2/episode/servers?episodeId=101574) , to get the server-episode-ids which would be server-id = **1031671** , and then after that I passed the server-id to the [https://zoro.to/ajax/v2/episode/sources?id=1031671](https://zoro.to/ajax/v2/episode/sources?id=1031671) to get the rapid-cloud iframe embed link ====> [https://rapid-cloud.co/embed-6/9qu8Z5OQUBZz?k=1](https://rapid-cloud.co/embed-6/9qu8Z5OQUBZz?k=1), after that I took the id **9qu8Z5OQUBZz** and passed it to the last link [https://rapid-cloud.co/ajax/embed-6/getSources?id=9qu8Z5OQUBZz](https://rapid-cloud.co/ajax/embed-6/getSources?id=9qu8Z5OQUBZz) to get sources  _**[NOTE: this wont work because id expires after some time just start over at [https://zoro.to/ajax/v2/episode/sources?id=1031671](url) to get new id]**_,....
And the results were this... 
```javascript
{"sources":"U2FsdGVkX1/hvbA4+9ZblUExPHJ9xYrmFWykhKLyUWz6vZt2Lr1EXiCj0tjGe5AesAt0YM5yYsqnCcphy2gDP6+Q+AziMCc7NY7Zn3R/Z3oETtE5/UYfXKmBIEhsuJSSFYHyGz6VUSbdRmhQMxEo/09NBQp7TP5w//Uyn411Z5QFLW0eq5/ccn5MzTloLcVvMqxvmw5TpgRUbPk1L1sDAe8S5ZugWaCbp6ayxQv9KGTiMqdocnNK9WxgfRaYBG2XW+7b0pXwQ9UxlV3WgF/bWf8k2wWM2QmnsnqEK2kRt9E+QO/x21Ei20D9olvpCbmON878B9hLfi7656aO3xjmsMVMeoILB7H1YN3qdGSnQUD+wIzi9OSdfRD6E2UwDZOaTcouFsenqf8B/Y26r66mQ+0cw3d2fQnqaJTm+XingF9v4k/59Arab0+NO/WgvRnwSrIbAWZ7xPH+Q31esqlXHbVt27/SM1QRNL3TRFbJaX3TGAajrXZgAnpt3macJwBHce2Nkm82A2J95P2+sRBWWQ==","sourcesBackup":"U2FsdGVkX19wYgmKVV9xFENO47rFmwhvgBFO4lavi90=","tracks":[{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/ara-6.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.zorores.com/4f/b6/4fb6c01963fcf630f1d468b74196afe3/4fb6c01963fcf630f1d468b74196afe3.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/eng-2.vtt","label":"English","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/fre-7.vtt","label":"French","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/ger-8.vtt","label":"German","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/ita-9.vtt","label":"Italian","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/por-3.vtt","label":"Portuguese - Portuguese(Brazil)","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/rus-10.vtt","label":"Russian","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/spa-5.vtt","label":"Spanish","kind":"captions"},{"file":"https://cc.zorores.com/26/bc/26bcf81ac53abecd2a8066e9f1c38f88/spa-4.vtt","label":"Spanish - Spanish(Latin_America)","kind":"captions"}],"encrypted":true,"intro":{"start":0,"end":0},"outro":{"start":0,"end":0},"server":1}
``` 

And as you can see the sources are encrypted with CryptoJs I presume... So can you guys help me figure out how to decrypt the sources any help would be appreciated.... 

### Solutions I tried...

1.  Obviously putting a the rapid-cloud link in to the iframe-src-attr, but this came with a fatal error...
2. Requesting the rapid-link in the backend and responding with the status 200 HTML code, and that lead to none-responsive code...
3. I tried reading the [https://rapid-cloud.co/js/player/prod/e6-player.min.js?v=1686106058](https://rapid-cloud.co/js/player/prod/e6-player.min.js?v=1686106058) to see if i can see how to get the keys to decrypt the sources, but this was one of the most painful things to do as a programmer, and i couldnt read it to see where the keys are....
4. I tried reverse engineering the minify code, but it was my first time doing that so i failed to figure it out, and plus they use hexidecimals to make it evening more stupidly difficult to read...
...And those are the solutions I tried...

And i again any help would be appreciated... Thank you xd

**Comment by illusionTBA** [comment]
take a look at [Consumets](https://github.com/consumet/consumet.ts) Repo, they have already solved decryption for zoro and 9anime

**Comment by illusionTBA** [comment]
i would just keep fetching from their once in a while or every time you want to decrypt a source

**Comment by thullyDev** [comment]
ok, thank you
